package cmd

import (
	"fmt"

	"github.com/penwyp/catmit/internal/ui"
	"github.com/spf13/cobra"
)

var (
	historyYes     bool   // skip confirmation and output directly
	historyLang    string // output language (en/zh)
	historyTimeout int    // timeout in seconds
	historyDebug   bool   // enable debug output for troubleshooting
	historyDryRun  bool   // preview without executing rebase
)

var squashHistoryCmd = &cobra.Command{
	Use:   "squash-history",
	Short: "Squash unpushed commits into a single commit",
	Long: `Squash-history command analyzes your unpushed commits and consolidates them 
into a single commit with a comprehensive message generated by LLM.

This command modifies your local git history by rebasing unpushed commits.
A backup branch is created before the operation for safety.`,
	Example: `  # Interactive mode with TUI
  catmit squash-history

  # Auto-squash without confirmation
  catmit squash-history --yes

  # Preview what would be squashed (dry run)
  catmit squash-history --dry-run

  # Chinese output with custom timeout
  catmit squash-history --lang zh --timeout 60`,
	RunE: runSquashHistory,
}

func init() {
	rootCmd.AddCommand(squashHistoryCmd)

	squashHistoryCmd.Flags().BoolVarP(&historyYes, "yes", "y", false, "Skip confirmation and execute directly")
	squashHistoryCmd.Flags().StringVarP(&historyLang, "lang", "l", "en", "Output language (en/zh)")
	squashHistoryCmd.Flags().IntVarP(&historyTimeout, "timeout", "t", 30, "Timeout in seconds")
	squashHistoryCmd.Flags().BoolVar(&historyDebug, "debug", false, "Enable debug output for troubleshooting")
	squashHistoryCmd.Flags().BoolVar(&historyDryRun, "dry-run", false, "Preview without executing rebase")
}

func runSquashHistory(cmd *cobra.Command, args []string) error {
	// Initialize dependencies
	deps, err := initSquashDependencies(historyDebug)
	if err != nil {
		return err
	}
	defer func() { _ = deps.logger.Sync() }()

	// Create context with timeout
	ctx, cancel := createContext(cmd, historyTimeout)
	defer cancel()

	// Create rebase workflow
	workflow, err := createRebaseWorkflow(ctx, deps.llmClient, historyLang, historyDebug, deps.logger)
	if err != nil {
		return fmt.Errorf("failed to create rebase workflow: %w", err)
	}

	// Analyze the repository
	analysis, err := workflow.Analyze(ctx)
	if err != nil {
		return fmt.Errorf("failed to analyze repository: %w", err)
	}

	if !analysis.CanRebase {
		fmt.Println(analysis.Message)
		return nil
	}

	// Generate commit message
	message, err := workflow.GenerateCommitMessage(ctx, analysis.UnpushedCommits)
	if err != nil {
		return fmt.Errorf("failed to generate commit message: %w", err)
	}

	// Handle dry-run mode
	if historyDryRun {
		fmt.Println("=== DRY RUN MODE ===")
		fmt.Printf("Would squash %d commits from branch '%s'\n", len(analysis.UnpushedCommits), analysis.CurrentBranch)
		fmt.Println("\nGenerated commit message:")
		fmt.Println(message)
		fmt.Println("\n=== END DRY RUN ===")
		return nil
	}

	// Handle yes mode
	if historyYes {
		fmt.Println("Generated commit message:")
		fmt.Println(message)

		// Execute rebase
		fmt.Println("\nExecuting rebase...")
		if err := workflow.ExecuteRebase(ctx, analysis, message); err != nil {
			return fmt.Errorf("rebase failed: %w", err)
		}

		fmt.Println("✓ Rebase completed successfully")
		return nil
	}

	// TUI mode
	model := ui.NewRebaseModel(workflow)
	if err := model.Run(); err != nil {
		return fmt.Errorf("TUI error: %w", err)
	}

	// If user accepted and rebase was successful
	if model.IsAccepted() {
		fmt.Println("\n✓ Rebase completed successfully")
		if backupBranch := model.GetBackupBranch(); backupBranch != "" {
			fmt.Printf("Backup branch: %s\n", backupBranch)
		}
	}

	return nil
}